hexapod/gazebo_ros_control/pid_gains:
  base_link__leg1_coxa: {p: 0.1, i: 0.1, d: 0.1}
  leg1_coxa__leg1_femur: {p: 0.1, i: 0.1, d: 0.1}
  leg1_femur__leg1_tibia: {p: 0.1, i: 0.1, d: 0.1}
 
  base_link__leg2_coxa: {p: 0.1, i: 0.1, d: 0.1}
  leg2_coxa__leg2_femur: {p: 0.1, i: 0.1, d: 0.1}
  leg2_femur__leg2_tibia: {p: 0.1, i: 0.1, d: 0.1}
 
  base_link__leg3_coxa: {p: 0.1, i: 0.1, d: 0.1}
  leg3_coxa__leg3_femur: {p: 0.1, i: 0.1, d: 0.1}
  leg3_femur__leg3_tibia: {p: 0.1, i: 0.1, d: 0.1}
 
  base_link__leg4_coxa: {p: 0.1, i: 0.1, d: 0.1}
  leg4_coxa__leg4_femur: {p: 0.1, i: 0.1, d: 0.1}
  leg4_femur__leg4_tibia: {p: 0.1, i: 0.1, d: 0.1}

  base_link__leg5_coxa: {p: 0.1, i: 0.1, d: 0.1}
  leg5_coxa__leg5_femur: {p: 0.1, i: 0.1, d: 0.1}
  leg5_femur__leg5_tibia: {p: 0.1, i: 0.1, d: 0.1}
 
  base_link__leg6_coxa: {p: 0.1, i: 0.1, d: 0.1}
  leg6_coxa__leg6_femur: {p: 0.1, i: 0.1, d: 0.1}
  leg6_femur__leg6_tibia: {p: 0.1, i: 0.1, d: 0.1}
      